const http = require('http');
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const PORT = process.env.PORT || 3000;

function parseJSONBody(req, cb) {
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', () => {
    try {
      const json = body ? JSON.parse(body) : {};
      cb(null, json);
    } catch (err) {
      cb(err);
    }
  });
}

function generateCertificatePDF({ name, course, date }, res) {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 60, bottom: 60, left: 60, right: 60 }
  });

  res.writeHead(200, {
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename="${(name || 'certificate').replace(/\s+/g, '_')}_certificate.pdf"`
  });

  doc.pipe(res);

  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;

  doc.save();
  doc.roundedRect(30, 40, pageWidth - 60, pageHeight - 80, 12)
     .lineWidth(3)
     .strokeColor('#2b6cb0') 
     .stroke();
  doc.restore();

  // Header
  doc.fontSize(28).fillColor('#1f2937').font('Times-Bold');
  doc.text('Certificate of Achievement', { align: 'center', underline: false });

  doc.moveDown(1);

  // Subtitle
  doc.fontSize(12).fillColor('#374151').font('Times-Roman');
  doc.text('This certificate is proudly presented to', { align: 'center' });

  doc.moveDown(0.8);

  // Name (big)
  doc.fontSize(26).fillColor('#0b5394').font('Times-Bold');
  doc.text(name || 'Recipient Name', { align: 'center' });

  doc.moveDown(0.6);

  // Course / reason
  doc.fontSize(14).fillColor('#374151').font('Times-Roman');
  doc.text(`For successfully completing the course:`, { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(16).fillColor('#0b5394').font('Times-Bold');
  doc.text(course || 'Course Title', { align: 'center' });

  doc.moveDown(2);

  // Date and signature area
  const leftX = 90;
  const rightX = pageWidth - 220;
  const y = doc.y + 20;

  // Draw signature line (right)
  doc.moveTo(rightX, y).lineTo(pageWidth - 80, y).lineWidth(1).strokeColor('#9CA3AF').stroke();
  doc.fontSize(12).fillColor('#374151').text('Authorized Signature', rightX, y + 6, { width: 140, align: 'center' });

  // Date (left)
  doc.fontSize(12).fillColor('#374151').text(`Date: ${date || new Date().toLocaleDateString()}`, leftX, y - 6, { width: 200, align: 'left' });

  // Small footer note
  doc.moveTo(60, pageHeight - 110).lineTo(pageWidth - 60, pageHeight - 110).lineWidth(0.5).strokeColor('#E5E7EB').stroke();
  doc.fontSize(9).fillColor('#6B7280').text('Generated by Certificate Generator • Built with Node.js + PDFKit', 0, pageHeight - 95, { align: 'center' });

  // finalize PDF
  doc.end();
}

// simple router + static server
const server = http.createServer((req, res) => {
  const { url, method } = req;

  if (url === '/api/generate' && method === 'POST') {
    return parseJSONBody(req, (err, body) => {
      if (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ ok: false, error: 'Invalid JSON' }));
      }
      // sanitize simple inputs
      const name = String(body.name || '').trim();
      const course = String(body.course || '').trim();
      const date = String(body.date || '').trim();
      return generateCertificatePDF({ name, course, date }, res);
    });
  }

  let reqPath = url === '/' ? '/certificatep.html' : url;
  reqPath = reqPath.replace(/\.\./g, '');
  const filePath = path.join(__dirname, 'public', reqPath);
  const ext = path.extname(filePath).toLowerCase();
  const contentType = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript'
  }[ext] || 'text/plain';

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Not Found');
      return;
    }
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`Certificate generator running on http://localhost:${PORT}`);
});
